# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: YjNjZDE4MGU0ZWRiYzMwZjZmNmRhZjY0YWM0ZWMzYTE5NDFjMDIzMGM4OTY3ZGM4MDM3NWQ5NWQxNDI1OWRjMmJjM2NjYzVjMWNkNjdiZWU0NmMxOTZlY2MzMDE3NDc2Njc0ODA1YTRkODhjZmUzODY2ZTcwZTZkODkzYTZhZDk=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
